controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

generate_pdf:
    path: /generate-pdf/{id}
    controller: App\Controller\CommandeController::generatePdf
