parameters:
    post_images_directory: '%kernel.project_dir%/public/uploads/posts'
    produit_images_directory: '%kernel.project_dir%/public/uploads/produits'
    KNP_SNAPPY_PDF_BINARY: '"%env(WKHTMLTOPDF_PATH)%"'  # Mettre des guillemets autour du chemin

services:
    Knp\Snappy\Pdf:
        class: Knp\Snappy\Pdf
        arguments:
            $binary: '%KNP_SNAPPY_PDF_BINARY%'  # Utilisation du paramètre avec guillemets

    # Default configuration for services in this file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Service\FactureService:
        arguments:
            $pdf: '@Knp\Snappy\Pdf'

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
